### ISSUE TITLE
PW 3.0.165 "Unrecognized operator: |"

### ISSUE THREAD

**Issue by gibson-sk** [Toutouwai/ConnectPageFields#3]
Many actions in admin control panel results in "Unrecognized operator: |" error message.
Exceptions log:
"Unrecognized operator: | (in \wire\core\Selectors.php line 410)"

Error disappears after uninstalling ConnectPage module.

**Comment by Toutouwai** [comment]
What version of ConnectPageFields are you running. If it's not the current v0.3.1 then you should update.

**Comment by gibson-sk** [comment]
Oh. Missed the July's update. Sorry. Works like clockwork on last version.
